### ISSUE TITLE
DB migration scripts

### ISSUE THREAD

**Issue by bachia** [project-sunbird/sunbird-devops#23]
Hi, can you please share DB (Cassandra & ES) migration scripts. Am trying to migrate our Sunbird installation from Sept 5th (v1.0) to current (v1.3). Let me know in case of any questions. 

@kochhar @mathewjpallan @Meethaz @Manojvv

**Comment by Manojvv** [comment]
@bachia 
Hi bachi, 

Cassandra setup for v1.3 is done on fresh installation or same old instance??

Point 1) If this is a new cassandra instance, `init-db.sh` script might have created required schema and tables. We should take the backup from the previous old  cassandra instance and restore in the new cassandra instance.

Point 2)If this is the same old cassandra instance, then `init-db.sh` might have done the updation of latest required schema and tables. And data already exists.

From later releases we are working on  some cassandra migration strategy , which is not available in release-1.3.  For migrating (v1.0) to current (v1.3) , you must follow any of the above points . 

Let me know. if you are using point-1 , we will provide you with cassandra backup and restore scripts. Those are not added to document because it is under testing. 
@rjshrjndrn Test the cassandra backup , restore & update the document, share the details with bachi.

Regards,
Manojvv

**Comment by bachia** [comment]
@Manojvv thank you for the detailed response. 

My current instance for testing is a fresh install. Meaning we just have to export data from production instance (Sunbird Sept 5th version) and import into current dev instance (Sunbird latest release as per latest devops code). I will wait for the scripts from @rjshrjndrn 

How about Elastic Search? Don't we have to rebuild indexes or something like that? 

@kochhar @mathewjpallan @Meethaz

**Comment by bachia** [comment]
Any update, please?

@kochhar @mathewjpallan @Meethaz @Manojvv

**Comment by Meethaz** [comment]
@rjshrjndrn Awaiting an update from your side based on the above response by @Manojvv 

cc @mathewjpallan

**Comment by Manojvv** [comment]
@rjshrjndrn Please update the status of this issue.

**Comment by rjshrjndrn** [comment]
@bachia @Manojvv 
The script is still in testing stage for large data, though it's working perfectly fine for me.

1. In old Cassandra instance, run [cassandra_complete_backup.sh](https://github.com/project-sunbird/sunbird-devops/blob/release-1.4/deploy/cassandra_complete_backup.sh)
2. copy over the tar to the new Cassandra instance
3. extract the tar
4. ./[cassandra_complete_restore.sh](https://github.com/project-sunbird/sunbird-devops/blob/release-1.4/deploy/cassandra_complete_restore.sh) </path/to/extracted parent folder>

eg: if you're in extracted dir `./cassandra_complete_restore.sh $(pwd)`

**Comment by bachia** [comment]
@rjshrjndrn Thank you. 

Do I have to pull latest devops repo to access these scripts?

**Comment by rjshrjndrn** [comment]
@bachia yes, please.
scripts will be in deploy/ folder.
